// examples/react/src/App.jsx
/*
 * Copyright 2023 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

import './App.css';
import {Provider, defaultTheme} from '@adobe/react-spectrum'
import {useState} from 'react'

import EnvironmentProvider from './EnvironmentProvider'

import DesignerView from './Designer';

function App() {
  let [selectedTheme, setTheme] = useState("light");

  const onThemeChange = () => {
    let selected = selectedTheme === "light" ? "dark" : "light";
    setTheme(selected);
  }

  return (
    <Provider theme={defaultTheme} 
              colorScheme={selectedTheme}
              height="100%">
      <div className="content-padding">
        <EnvironmentProvider>
            <DesignerView colorScheme={selectedTheme} onThemeChange={onThemeChange}/>
        </EnvironmentProvider>
      </div>
    </Provider>
  );
}

export default App;

// examples/angular/src/app/app.component.ts
/*
 * Copyright 2023 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular';
}


<!--
Copyright 2023 Adobe. All rights reserved.
This file is licensed to you under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License. You may obtain a copy
of the License at http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under
the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
OF ANY KIND, either express or implied. See the License for the specific language
governing permissions and limitations under the License.
-->


<div class="page">
  <header class="page-header">
    <h1>Example Integration of Content Advisor in Angular</h1>
  </header>
  <main class="page-content">
    <asset-selector></asset-selector>
  </main>
</div>

<router-outlet></router-outlet>
